---
ID: "e8bdb7bb-dfed-471f-a55e-ab4ddeda71c9"
Parent: "30d8da8e-3331-4125-abb3-f7fd3e5b72b7"
Template: "30d8da8e-3331-4125-abb3-f7fd3e5b72b7"
Path: "/sitecore/templates/Feature/assurex-cloud/Cart/Rendering Parameters/Cart/__Standard Values"
SharedFields:
- ID: "06d5295c-ed2f-4a54-9bf2-26228d113318"
  Hint: __Icon
  Value: apps/32x32/carts.png
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20211012T120926Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\JssImport
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "42edc5fa-1e5b-4cbc-8b7a-f655857f81a9"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\mohd.kashif@assurex.co
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20231006T134946Z
