---
ID: "7446b909-4776-4d2d-b4d6-d0361b2ad9cc"
Parent: "adc7811f-adeb-45b7-aa46-00c77f3320df"
Template: "adc7811f-adeb-45b7-aa46-00c77f3320df"
Path: "/sitecore/templates/Feature/assurex-cloud/Social List/Social List Root/__Standard Values"
SharedFields:
- ID: "1172f251-dad4-4efb-a329-0c63500e4f1e"
  Hint: __Masters
  Value: "{52AB4F8B-C8C6-4616-9F61-75EEFA27A3BF}"
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20120621T071508Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\admin
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "b8fb36db-aec8-4fae-8ce0-c97b43e44750"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\rekha@assurex.co
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20230929T135553Z
