---
ID: "a5a98954-02eb-44fc-a03f-7ff92be7096b"
Parent: "122af3a0-54a6-413f-8363-1090b8468279"
Template: "122af3a0-54a6-413f-8363-1090b8468279"
Path: "/sitecore/templates/Feature/assurex-cloud/Subscribe/ImageList/__Standard Values"
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20240404T122314Z
    - ID: "52807595-0f8f-4b20-8d2a-cb71d28c6103"
      Hint: __Owner
      Value: |
        sitecore\arun@assurex.co
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\arun@assurex.co
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "2cbad99b-63d6-4eb9-a41d-fc76cc1e906f"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\arun@assurex.co
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20240404T122314Z
