---
ID: "0d192daa-8e0e-45ce-bd78-c1b0c99e3158"
Parent: "74f59dc9-1ac2-4a47-a8be-dd87776e7acc"
Template: "74f59dc9-1ac2-4a47-a8be-dd87776e7acc"
Path: "/sitecore/templates/Feature/assurex-cloud/CSRReport/CSRReport Folder/__Standard Values"
SharedFields:
- ID: "1172f251-dad4-4efb-a329-0c63500e4f1e"
  Hint: __Masters
  Value: |
    {74F59DC9-1AC2-4A47-A8BE-DD87776E7ACC}
    {8108AAE9-FF6C-430D-B2B5-E6BF38BC84EE}
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20120621T071508Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\admin
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "755b4808-2d84-48d6-8c7b-9976fc0100e2"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\Mohd Kashif
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20240327T074305Z
