---
ID: "3a8342fa-6a49-42b9-8572-3a94c51157ee"
Parent: "f46328b2-13d1-4f45-a7fb-01c9c1abea43"
Template: "f46328b2-13d1-4f45-a7fb-01c9c1abea43"
Path: "/sitecore/templates/Feature/assurex-cloud/Forms/Form/__Standard Values"
SharedFields:
- ID: "1172f251-dad4-4efb-a329-0c63500e4f1e"
  Hint: __Masters
  Value: "{CAE34489-E803-4604-B68D-D37AD98A74EF}"
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20231010T091603Z
    - ID: "52807595-0f8f-4b20-8d2a-cb71d28c6103"
      Hint: __Owner
      Value: |
        sitecore\rekha@assurex.co
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\rekha@assurex.co
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "8306852e-72c1-42cc-9ed1-3bf37ad6034b"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\rekha@assurex.co
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20231010T101128Z
