---
ID: "477d9312-45c8-4b75-a4d7-8f58bd5a8595"
Parent: "4c74573c-8956-46e1-a5c1-ea12fb2f0f42"
Template: "4c74573c-8956-46e1-a5c1-ea12fb2f0f42"
Path: "/sitecore/templates/Feature/assurex-cloud/Forms/Form Folder/__Standard Values"
SharedFields:
- ID: "1172f251-dad4-4efb-a329-0c63500e4f1e"
  Hint: __Masters
  Value: "{F46328B2-13D1-4F45-A7FB-01C9C1ABEA43}"
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20231010T101540Z
    - ID: "52807595-0f8f-4b20-8d2a-cb71d28c6103"
      Hint: __Owner
      Value: |
        sitecore\rekha@assurex.co
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\rekha@assurex.co
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "91c38709-626b-4084-898d-dfdfea3fb320"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\rekha@assurex.co
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20231010T101554Z
