---
ID: "4ac51709-14b6-4406-a53b-ed7fa07b60df"
Parent: "3ec0e7da-5ac4-4b66-a730-93c22e39e259"
Template: "3ec0e7da-5ac4-4b66-a730-93c22e39e259"
Path: "/sitecore/templates/Feature/assurex-cloud/Social Media/Rendering Parameters/Social/__Standard Values"
SharedFields:
- ID: "06d5295c-ed2f-4a54-9bf2-26228d113318"
  Hint: __Icon
  Value: people/32x32/users3_add.png
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20211012T120926Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\JssImport
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "18bc1294-5b11-487b-85aa-b10c359f9aaf"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\mohd.kashif@assurex.co
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20230905T055541Z
