---
ID: "7ff04e3a-44fc-4acd-ae0e-de94b4945992"
Parent: "bd09e928-bf34-41c1-9c8f-92bbab7c7045"
Template: "bd09e928-bf34-41c1-9c8f-92bbab7c7045"
Path: "/sitecore/templates/Feature/assurex-cloud/MyProfile/Section/__Standard Values"
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20230908T112014Z
    - ID: "52807595-0f8f-4b20-8d2a-cb71d28c6103"
      Hint: __Owner
      Value: |
        sitecore\mohd.kashif@assurex.co
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\mohd.kashif@assurex.co
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "8c92fb5d-8ec4-488d-a017-f0a9a2896957"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\rekha@assurex.co
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20231018T104019Z
    - ID: "e1c9b104-3b14-47b3-8796-79b354d1e540"
      Hint: Key
      Value: $name
