---
ID: "c2369a3c-4008-4afa-b18e-023d6d2bb7e6"
Parent: "f6478765-8f71-449b-9184-592bf8110d92"
Template: "f6478765-8f71-449b-9184-592bf8110d92"
Path: "/sitecore/templates/Feature/assurex-cloud/FeaturedProducts/Rendering Parameters/FeaturedProducts/__Standard Values"
SharedFields:
- ID: "06d5295c-ed2f-4a54-9bf2-26228d113318"
  Hint: __Icon
  Value: "apps/32x32/fire-balloon.png"
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20211012T120926Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\JssImport
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "241f6e91-4cf0-4cff-ae7d-b6fde07f33e2"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\mohd.kashif@assurex.co
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20231003T133759Z
